<html>
<head>
    <style>
        ul.lightspeed{
            list-style: none;
            margin-left: 50px;
            margin-bottom: 20px;
        }
    </style>
    <script type="text/javascript">
        function checkAllProducts(checked){
            var checkboxes = $('productForm').select('.productCheckbox');
            checkboxes.each(function(checkbox){
                checkbox.checked = checked;
            });
        }
    </script>
</head>
<body>
<?php $groups = $this->getProducts(); ?>
<p>
    Please select the product you want to sync below.<br />
</p>
<?php if(count($groups) > 0):?>
    <form id="productForm" method="post" action="<?php echo $this->getLightSpeedUrl('sync') ?>">
        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
        <?php foreach($groups as $group):?>
            <h3><?php echo $this->decodeName($group["name"]); ?></h3>
            <ul class="lightspeed">
                <?php if(isset($group["products"])):?>
                    <?php foreach($group["products"] as $product):?>
                        <?php if($product->visible && $product->name != "LINE" && $product->name != "SPACER" && $product->productType == ""):?>
                            <li>
                                <input class="productCheckbox" type="checkbox" id="<?php echo $product->id;?>" name="<?php echo $product->id;?>" value="<?php echo $group["id"]; ?>"/>
                                <label for="<?php echo $product->id;?>"><?php echo $product->name.' ('.$product->sku.')'.' - '.$this->formatPrice($this->getPrice($product, false)).' ('.$this->formatPrice($this->getPrice($product, true)).' VAT Incl.)'; ?></label>
                            </li>
                        <?php endif;?>
                    <?php endforeach; ?>
                <?php else: ?>
                    <p>No products were found for this group.</p>
                <?php endif; ?>
            </ul>
        <?php endforeach;?>
        <button id="selectProducts" title="Select products" type="submit" class="scalable"><span><span><span>Select Products</span></span></span></button>
        <button id="selectAll" type="button" class="scalable" onclick="checkAllProducts(true)"><span><span><span>Select all</span></span></span></button>
        <button id="deSelectAll" type="button" class="scalable" onclick="checkAllProducts(false)"><span><span><span>Deselect all</span></span></span></button>
    </form>
<?php else: ?>
    <p>No product groups found. Please add a group first using the Lightspeed Restaurant Manager.</p>
<?php endif; ?>
</body>
</html>

