<html>
<head>
    <style>
        ul.lightspeed{
            list-style: disc;
            margin-left: 50px;
            margin-bottom: 20px;
        }
    </style>
</head>
<body>
<?php $errors = $this->checkSync(); ?>
<?php if(count($errors) > 0):?>
    <p>
        Your configuration is not complete yet.<br />
        Please fill in the following fields in the Lightspeed configuration:
    </p>
    <ul class="lightspeed">
        <?php foreach($errors as $value):?>
            <li><?php echo $value; ?></li>
        <?php endforeach; ?>
    </ul>
    <button id="goToLightspeedConfig" title="Go to configuration" type="button" class="scalable" onclick="setLocation('<?php echo $this->getConfigUrl() ?>')" style=""><span><span><span>Go to configuration</span></span></span></button>
<?php else: ?>
    <p>Which customers do you want to sync?</p>
    <form method="post" action="<?php echo $this->getLightSpeedUrl('sync') ?>">
        <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
        <select id="syncField" name="syncField">
            <option value="all">All customers</option>
            <option value="existing">Existing customers</option>
            <option value="new">New customers</option>
        </select>
        <button id="startSyncing" title="Start syncing" type="submit" class="scalable"><span><span><span>Start Syncing</span></span></span></button>
    </form>
<?php endif; ?>
</body>
</html>

