<html>
<head>
    <style>
        ul.lightspeed{
            list-style: disc;
            margin-left: 50px;
            margin-bottom: 20px;
        }
    </style>
</head>
<body>
    <?php $errors = $this->checkSync(); ?>
    <?php if(count($errors) > 0):?>
        <p>
            Your configuration is not complete yet.<br />
            Please fill in the following fields in the Lightspeed configuration:
        </p>
        <ul class="lightspeed">
            <?php foreach($errors as $value):?>
                <li><?php echo $value; ?></li>
            <?php endforeach; ?>
        </ul>
        <button id="goToLightspeedConfig" title="Go to configuration" type="button" class="scalable" onclick="setLocation('<?php echo $this->getConfigUrl() ?>')" style=""><span><span><span>Go to configuration</span></span></span></button>
    <?php else: ?>
        <p>On what field do you want to sync the products?</p>
        <form method="post" action="<?php echo $this->getLightSpeedUrl('categories') ?>">
            <input name="form_key" type="hidden" value="<?php echo Mage::getSingleton('core/session')->getFormKey() ?>" />
            <select id="priceField" name="priceField">
                <option value="price">Normal price</option>
                <option value="takeawayPrice">Take-away price</option>
                <option value="deliveryPrice">Delivery price</option>
            </select>
            <button id="startSyncing" title="Start syncing" type="submit" class="scalable"><span><span><span>Start Syncing</span></span></span></button>
        </form>
    <?php endif; ?>
</body>
</html>

