<html>
    <head>
        <style>
            .hide {
                display: none;
            }

            .details {
                background-color: #fff9e9;
            }

            .previousPage {
                float: left;
            }

            .nextPage {
                float: right;
            }

            .pager {
                height: 30px;
            }

            .filter {
                left: 50%;
                position: absolute;
                -ms-transform: translate(-50%,0%); /* IE 9 */
                -webkit-transform: translate(-50%,0%); /* Safari */
                transform: translate(-50%,0%);
            }

            .filter select {
                width: 200px !important;
            }
        </style>
        <script type="text/javascript">
            function toggleDetails(id){
                $('detail-'+id).toggleClassName('hide');
            }
        </script>
    </head>
    <body>
        <?php $orders = $this->getOrders(); ?>
        <div class="pager">
            <?php if($this->previousPage): ?>
                <a class="previousPage" href="<?php echo $this->getPreviousPage();?>">
                    <img src="/skin/adminhtml/default/default/images/pager_arrow_left.gif" alt="Go to Previous page" class="arrow">
                    Previous
                </a>
            <?php endif; ?>
            <form method="get" action="<?php echo $this->getUrl('adminhtml/monitor/index') ?>" class="filter">
                <input type="hidden" id="offset" name="offset" value="0">
                <select id="status" name="status">
                    <?php foreach($this->statuses as $name => $id): ?>
                    <option value="<?php echo $id; ?>" id="<?php echo $id; ?>"<?php if($this->status == $id){ echo 'selected="selected"';} ?>><?php echo $name; ?></option>
                    <?php endforeach; ?>
                </select>
                <button type="submit" class="scalable"><span><span><span>Filter</span></span></span></button>
            </form>
            <?php if($this->nextPage): ?>
                <a class="nextPage" href="<?php echo $this->getNextPage();?>">
                    Next
                    <img src="/skin/adminhtml/default/default/images/pager_arrow_right.gif" alt="Go to Previous page" class="arrow">
                </a>
            <?php endif; ?>
        </div>
        <div class="grid">
            <div class="hor-scroll">
                <table cellspacing="0">
                    <thead>
                    <tr class="headings">
                        <th>Order id</th>
                        <th>Lightspeed Receipt Id</th>
                        <th>Customer</th>
                        <th>Total Price</th>
                        <th>Type</th>
                        <th>Status</th>
                        <th class="last">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php for($index = 0; $index < count($orders); $index++):?>
                        <tr class="<?php echo 'pointer '.($index % 2 == 0 ? 'even' : ''); ?>">
                            <td>
                                <?php if (isset($orders[$index]->magentoId)): ?>
                                    <a href="<?php echo $orders[$index]->magentoLink?>"><?php echo $orders[$index]->magentoIncId?></a>
                                <?php else:?>
                                    -
                                <?php endif; ?>
                            </td>
                            <td><?php echo $orders[$index]->receiptId; ?></td>
                            <td><?php echo (isset($orders[$index]->customerName) ? $orders[$index]->customerName : '-'); ?></td>
                            <td><?php echo $orders[$index]->totalPrice; ?></td>
                            <td><?php echo $orders[$index]->type; ?></td>
                            <td><?php echo $orders[$index]->status; ?></td>
                            <td>
                                <?php if(isset($orders[$index]->magentoId)): ?>
                                    <a href="<?php echo $this->getReorderUrl($orders[$index]->magentoId)?>">Retry</a>
                                <?php else: ?>
                                    &nbsp;
                                <?php endif; ?>
                            </td>
                        </tr>
                        <!--tr id="detail-<?php echo $orders[$index]->id; ?>" class="hide details" >
                            <td colspan="6" class="last">
                                order information
                            </td>
                        </tr-->
                    <?php endfor; ?>
                    </tbody>
                </table>
            </div>
        </div>
    </body>
</html>